### ISSUE TITLE
Void doesn't end recursion

### ISSUE THREAD

**Issue by apalala** [neogeny/TatSu#116]
```python
    def test_nullable_void(self):
        left_grammar = '''
            @@left_recursion :: True
            @@nameguard :: False

            start = A $ ;
            A = | A 'a' | () ;
        '''

        assert [['a', 'a'], 'a'] == parse(left_grammar, 'aaa')  # warning: infinite recursion
```

**Comment by Victorious3** [comment]
It discards (the correct) last result because `()` doesn't grow the seed at all. Might need special casing. I could also try to do just one more iteration when it doesn't grow the seed and take that, but I'm not sure what side effects this would have.

**Comment by Victorious3** [comment]
I mean when I think about it, having it not terminate is technically correct as there are an infinite amount of `()`s before the first a. I don't think that's how PEG is supposed to work but the left recursion is already breaking some other assumptions.
```
A = A 'a' | 'a' ;
```
works as intended.

What I could do is figuring out if there "was" a null match and then terminating the left recursion but that isn't exactly a simple thing to do since I can't logically separate `| A 'a' |` and only do `'a'` part. I might be able to do it for simple cases like this one but when it becomes more complex with nested rules I can't figure out which part of the rule is supposed to be left recursive and which part isn't.

**Comment by apalala** [comment]
I agree with your analysis, @Victorious3 . 

`A = | A 'a' | () ;` is incorrect in PEG, and should probably produce an error while parsing the grammar.

**Comment by norswap** [comment]
Is the initial `|` supposed to mean that there is a first empty alternative? Then according to ordered choice, the rule should succeeds while matching no input.

But if that interpretation is correct, then I'm not sure what `()` is — I thought this meant *empty*.

Anyhow, for a rule that is `A ::= A 'a' | empty`, the correct match for "aaa" is `[[[empty, 'a'], 'a'], 'a']`. On the first go, recursion is disabled, `A` matches `empty`, on the second go, the recursion yields `empty` and the first `a` is matched, on the third go the recursion matches the first `a` and the second `a` is matched, etc.

Since this is related to @apalala's recent [PEG mailing list mail](https://lists.csail.mit.edu/pipermail/peg/2019-April/000743.html) (answering to [this thread](https://lists.csail.mit.edu/pipermail/peg/2018-March/thread.html)), I'll also ask here so as not to pollute the mailing list too much:

Why do you think that `A -> A 'a' / empty` matches `empty*`? I'm really confused by that. Seems perfectly fine by me (cf. that very example just above).

Another comment I'll put here — that thread mentions the rule `A -> A 'a' | 'a' A | empty` and I've seen some tests on "associativity" being done on TatSu.

This rule is pathological and useless in practice, but nevertheless VERY interesting, for multiple reasons. First, under my algorithm* (and I presume, TatSu's?), the result that is always right-associative, which is not what one may naively expect, but makes perfect sense given the algorithm: at each input position, left-recursion becomes blocked, but right recursion can proceed. We then attempt to grow the seed at each position, but this is not possible because the whole of it has already been consumed... so actually left-recursion fails at every position and then we re-perform right-recursion.

The second reason is that, under this algorithm, this has exponential runtime: for each input position, we need to try the first alternative (left-recursion), which causes us to try the second alternative (right-recursion) at the same position, which causes the same thing to happen at the next position (invocations at the next position = 1). When that (left-recursion) fails, we now need to try the second alternative (again), which causes the whole process at the next position again (invocation at the next position = 2). So you end up invoking `A` 2^n times at position n.

(*) I actually have two algorithms depending on associativity selection. The above is done with the default one, which "privileges" right-recursion (as we see happens in the example above). The left-associative one is actually bugged in the paper (it never allows right-recursion, making it somewhat useless) — nevertheless the version in the paper would handle this (admittedly pathological) grammar and produce a left-associative parse (simply by virtue of blocking the right-recursion). The corrected version will also yield a left-recursive parse, but the right-recursive rule will succeed once: e.g. `[{a, a}, a]` for "aaa" where curly brackets show the right-recursive alternative match.

For what it's worth, I'm not sure it's possible to handle these pathological cases gracefully. One potential solution is to force the memoization of a *completed* (after full seed-growing) left-recursive rule. But that would break if there is interleaved left-recursion, e.g.:

`A ::= B a`
`B ::= A b | b`

For this reason and others (notably, the semantics of left-recursion in the presence of associativity selection is really hard to formulate for non-trivial cases), I've actually given up on "transparent left-recursion" (e.g. `A ::= A '+' A | a`) in Autumn. Instead I use explicit left- and right-associativity combinators (e.g. `A ::= left_assoc('a', '+')`) These are explained [here](https://github.com/norswap/autumn4/blob/master/doc/A6-left-recursion-associativity.md), followed by an explanation of the old method and why it shouldn't be used. The [code for the old method ](https://github.com/norswap/autumn4/blob/master/src/norswap/autumn/parsers/LeftRecursive.java)is still there though, including a comment on how I choose to define the semantics of left-associativity.

**Comment by Victorious3** [comment]
The first `|` is only for visuals, so that you can write:
```
R = | ...
    | ...
```
Anyway. 

```
A = | A 'a' | () ;
```
fails because of the algorithm here:
https://github.com/neogeny/TatSu/blob/bd7fea0ba31234ca49f6ce0b401677849483f329/tatsu/contexts.py#L561-L574

What's happening is that it starts growing the seed, gets `()` (which is just an empty match), and then decides that the seed didn't grow, so the result isn't saved. At this point the result stack only contains the  dummy exception to prevent infinite left recursion, so I get that as error message.

I guess comparing the string length of the match is not sufficient enough. I have a few ideas how this could be improved by keeping track of the successful matches instead (and if they were null matches or not) but nothing concrete yet.

**Comment by norswap** [comment]
Ah, but then the fix is really easy, no: just initialize `lastpos` to a negative (or something in that vein).

I checked, it's indeed what I do [in my implem](https://github.com/norswap/autumn4/blob/master/src/norswap/autumn/parsers/LeftRecursive.java): the seed is represented by an instance of `Invocation` and before finding the initial seed, it's initialized with a dummy that has `end_pos == -1`.

Blocked recursion: well if you don't support forcing left-associativity for rules that are both left- and right-associative (the "second algorithm" I mention before), then only left-recursion is blocked, which of course you need to in order to avoid infinite recursion, so I assume you already do that.

**Comment by Victorious3** [comment]
That sounds almost too easy to...
Work. It does.

Oh well. Thanks a lot!

**Comment by apalala** [comment]
Very cool, @norswap , @Victorious3 !
