### ISSUE TITLE
python example generates parser with invalid syntax

### ISSUE THREAD

**Issue by lllama** [neogeny/TatSu#46]
```
tatsu.exe --outfile .\test.py .\python.ebnf
python .\test.py
  File ".\test.py", line 1272
    self._pattern(r'["\\']')
                         ^
SyntaxError: invalid syntax
```
I think this is in the `TRIAPOS` definition.

**Comment by apalala** [comment]
@lllama The Python example is not an _official_ part of the distribution. That's why it's undocumented. 

I've meant to remove it until I have time to work on it, probably from scratch, and likely overhauling `g2t`.

As mentioned in other replies to issue posts, it's best to first ask on StackOverflow with the `[tatsu]` tag.

**Comment by lllama** [comment]
It was more that the tool accepts the grammar as valid and generates a parser that is invalid python, which suggests that there is an issue with the code generation.

**Comment by apalala** [comment]
@lllama 

There need's to be much more work in the way ANTLR tokenizers are translated to TatSu rules. 

As it is, `g2t`will produce parsers that are mostly correct, easy to understand, but sometimes invalid (yet easy to repair).

In previous work I've done the lexical part from scratch, by hand, because I don't like the complex way it is done in ANTLR, and because I haven't needed the parser to be strict.
